implementación de server
GastonStinson/ArtTechStore pull request #1
Opened 2023-08-28 22:05 UTC by ioskpu

se crea el index js para levantar el server en port 3000, se instalan dependencias a continuación: axios, cors, dotenv, express, socket.io, uuid y se crea archivo gitignore

2023-08-28 22:12 UTC, FelixGitHu requested changes
Me parece muy bien pero pense que se iba a hacer el proyecto en Typescrit. Hay que hacer eso o podemos hacer mix?

2023-08-28 22:17 UTC, santiredo reviewed
No deberian ir los package.json dentro de la carpeta server?

2023-08-28 22:27 UTC, ioskpu commented
> Me parece muy bien pero pense que se iba a hacer el proyecto en Typescrit. Hay que hacer eso o podemos hacer mix?

ahh ok, listo ya hago cambios Felix

2023-08-28 22:29 UTC, ioskpu commented
> No deberian ir los package.json dentro de la carpeta server?

depende de como hagamos el deploy .. pero si tienes razon para dejarlo mas limpio entonces metamos el pakage json dentro y para el front utilizamos otro pakakage

2023-08-29 14:04 UTC, santiredo approved these changes

2023-08-29 14:06 UTC, GastonStinson approved these changes

2023-08-29 14:08 UTC, merged